# Generated by Django 4.1 on 2022-08-10 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='total_votes',
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.IntegerField()),
                ('author_fk', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='voter', to='post.dummyuser')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('author_fk', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to='post.dummyuser')),
            ],
            options={
                'ordering': ('-published_at',),
            },
        ),
        migrations.AddField(
            model_name='post',
            name='comment_fk',
            field=models.ManyToManyField(blank=True, to='post.comment'),
        ),
        migrations.AddField(
            model_name='post',
            name='vote_fk',
            field=models.ManyToManyField(blank=True, to='post.vote'),
        ),
    ]
