# Generated by Django 4.1 on 2022-08-15 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_dummyuser_remove_post_total_votes_vote_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('published_at',)},
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='author_fk',
            new_name='voter_fk',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author_fk',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comment_fk',
        ),
        migrations.RemoveField(
            model_name='post',
            name='vote_fk',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
        migrations.AddField(
            model_name='comment',
            name='post_fk',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='post.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='post_fk',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='post_votes', to='post.post'),
            preserve_default=False,
        ),
    ]
