# Generated by Django 4.1 on 2022-08-15 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_at']},
        ),
    ]
